spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    #url: jdbc:mysql://58.215.87.40:5306/cqwork?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #url: jdbc:mysql://192.168.208.1:3306/ework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    url: jdbc:mysql://localhost:3306/ework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 666666
    tomcat:
      jmx-enabled: true
      validation-query: SELECT 1
      max-active: 100
      max-wait: 10000
      max-idle: 100
      min-idle: 10
      test-on-borrow: true
      test-while-idle: false
      test-on-return: false
      validation-interval: 30000
      time-between-eviction-runs-millis: 30000
      initial-size: 10
      remove-abandoned-timeout: 60
      log-abandoned: true
      remove-abandoned: true
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;
    

system-param: 
    imgpath: D:\\tupian\\
