spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://127.0.0.1:3306/cqwork?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: cqshj1
    tomcat:
      jmx-enabled: true
      validation-query: SELECT 1
      max-active: 100
      max-wait: 10000
      max-idle: 100
      min-idle: 10
      test-on-borrow: true
      test-while-idle: false
      test-on-return: false
      validation-interval: 30000
      time-between-eviction-runs-millis: 30000
      initial-size: 10
      remove-abandoned-timeout: 60
      log-abandoned: true
      remove-abandoned: true
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer;

system-param: 
    imgpath: /home/errorimage/
    